name: dl_a2
channels:
  - pytorch
  - defaults
dependencies:
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.3.11
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cpuonly=2.0
  - filelock=3.13.1
  - freetype=2.12.1
  - gmp=6.2.1
  - gmpy2=2.1.2
  - idna=3.7
  - jinja2=3.1.3
  - jpeg=9e
  - lcms2=2.12
  - lerc=3.0
  - libcxx=14.0.6
  - libdeflate=1.17
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libjpeg-turbo=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.1
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openjpeg=2.3.0
  - openssl=3.0.13
  - pillow=10.3.0
  - pip=23.3.1
  - pysocks=1.7.1
  - python=3.11.9
  - pytorch=2.3.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - sqlite=3.45.3
  - sympy=1.12
  - tk=8.6.12
  - torchaudio=2.3.0
  - torchvision=0.18.0
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - wheel=0.41.2
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - annotated-types==0.6.0
      - appdirs==1.4.4
      - blis==0.7.11
      - catalogue==2.0.10
      - click==8.1.7
      - cloudpathlib==0.16.0
      - confection==0.1.4
      - cymem==2.0.8
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - joblib==1.4.0
      - langcodes==3.4.0
      - language-data==1.2.0
      - marisa-trie==1.1.0
      - murmurhash==1.0.10
      - nltk==3.8.1
      - packaging==24.0
      - pandas==2.2.2
      - preshed==3.0.9
      - protobuf==4.25.3
      - psutil==5.9.8
      - pydantic==2.7.1
      - pydantic-core==2.18.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.1
      - regex==2024.4.28
      - sentry-sdk==2.0.1
      - setproctitle==1.3.3
      - six==1.16.0
      - smart-open==6.4.0
      - smmap==5.0.1
      - spacy==3.7.4
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - srsly==2.4.8
      - thinc==8.2.3
      - tqdm==4.66.2
      - typer==0.9.4
      - tzdata==2024.1
      - wandb==0.16.6
      - wasabi==1.1.2
      - weasel==0.3.4
